### PR TITLE
Include instructions for Hawkular APM

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
This PR replaces the original #15 written by Juca, with the updated oc deploy commands to avoid using the docker image due to the manifest issue between openshift and docker hub.

@rafabene Could you check these updated instructions please, to see if they work fine for you?

**Comment by jpkrohling** [comment]
Any news on this one?

**Comment by objectiser** [comment]
@jpkrohling awaiting review and testing - do the updated instructions look ok to you?

**Comment by jpkrohling** [comment]
It looks OK, although I'd need more time to test it.

**Comment by rafabene** [comment]
Hi @jpkrohling an @objectiser . I was in PTO the last couple of days. Since I've returned today I should handle this PR soon. Thanks for your patience.

**Comment by rafabene** [comment]
I just tried this PR and it seems to work nicely. However it would be good to add instructions on how to setup the ReadinessProbe given that the server takes almost 2 minutes to boot and start serving requests.

I'll merge this PR, but if you can send another one with the ReadinessProbe I'll appreciate.

**Comment by rafabene** [comment]
Merged in commit https://github.com/redhat-helloworld-msa/helloworld-msa/commit/2d06f44b1b3c4b25df036a06a838b18704c1b3d8

**Pull request closed without merging**
