### PR TITLE
Bump zipkin to 1.19.2

### PR DESCRIPTION
**Pull request by pavolloffay**
Currently used zipkin version is quite old. This bumps to the newest version provided by fabric8.

Concretely I run into this issue: https://github.com/openzipkin/zipkin/issues/1085. It should be fixed in the newer version.

### CODE REVIEW

**Comment by pavolloffay** [comment]
@rafabene could you please review, test and eventually merge. There is a series of PRs to other services because `zipkin-query` has been renamed to `zipkin`. I also run into issue with:

```yml
# If your application uses an special SCC, uncomment the following line to adjust the SCC
adjust_scc: true
```
zipkin-openshift is failing with it (mysql database) I had to switch it back to `false` and change frontend's Dockerfile https://github.com/redhat-helloworld-msa/frontend/pull/11.

Note that this only fixes ansible and manual installation, if you could tell me how to do change the `Option 1` I'm happy to proceed.  

cc @jpkrohling @objectiser

**Comment by rafabene** [comment]
Hi @pavolloffay.  How this PR relates to #24 ?

**Comment by rafabene** [comment]
I was able to fix the https://github.com/redhat-helloworld-msa/frontend/ and thes ansible script to remove the need to "adjust_scc".

**Comment by pavolloffay** [comment]
@rafabene 

> Hi @pavolloffay. How this PR relates to #24 ?

This does not relates to #24, however it relates to https://github.com/redhat-helloworld-msa/ola/pull/4. But anyway I think this is beneficial for the project because it updates quite old zipkin version to the new one.


> I was able to fix the https://github.com/redhat-helloworld-msa/frontend/ and thes ansible script to remove the need to "adjust_scc".

Yes it uses the same fix from my PR. (I have rebased it)

**Comment by pavolloffay** [comment]
@rafabene PR rebased. I saw your commit https://github.com/redhat-helloworld-msa/helloworld-msa/commit/45de444313173599d483f65e14363d1e41451707:

 however `zipkin-starter-minimal/0.1.1` and `zipkin-starter-minimal/0.0.8` use the same zipkin version: 
* https://github.com/fabric8io/kubernetes-zipkin/blob/v0.1.1/pom.xml#L79
* https://github.com/fabric8io/kubernetes-zipkin/blob/v0.0.8/pom.xml#L81

so this PR is still needed.

**Comment by rafabene** [comment]
Ok. I should work on the update today.

**Comment by rafabene** [comment]
Solved in this commit: https://github.com/redhat-helloworld-msa/helloworld-msa/commit/6a8110589c25eac8acd7223d2bf91995c0b72db8

**Comment by pavolloffay** [comment]
@rafabene thanks!

**Pull request closed without merging**
