### PR TITLE
Jaeger tracing

### PR DESCRIPTION
**Pull request by pavolloffay**
- [x] Use tagged Jaeger version - f209812d
- [x] Change the picture in the root readme with jaeger

### CODE REVIEW

**Comment by pavolloffay** [comment]
Update: this is getting to the final state. Now we are waiting for a tagged version of Jaeger image, then it can be tested and merged.

cc @jpkrohling @objectiser @burrsutter @rafabene

**Comment by objectiser** [comment]
@pavolloffay Tested invoking api-gw via curl, and scaling down aloha to test fallback - all displayed correctly in Jaeger UI.

**Comment by pavolloffay** [comment]
Updated version of Jaeger OC template with readinessprobe.

@rafabene all other PRs have been merged, what is missing to merge this one?

**Comment by rafabene** [comment]
PR merged

**Pull request closed without merging**
